apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: job-scraper-app-data
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "job-scraper.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.pvc.app.storageClass }}
  resources:
    requests:
      storage: {{ .Values.pvc.app.size }}
